# Generated by Django 3.2.8 on 2021-10-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20211022_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_product',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
