# Generated by Django 3.2.8 on 2021-10-27 10:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_cart_total_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=28)),
                ('address', models.CharField(blank=True, max_length=2535, null=True)),
                ('status', models.CharField(choices=[('completed', 'order is completed'), ('completed', 'new order'), ('in_progress', 'order in progress'), ('is_ready', 'order is ready')], default='NEW', max_length=255)),
                ('buying_type', models.CharField(choices=[('delivery', 'delivery'), ('pickup', 'pickup')], default='pickup', max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Order received date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='shop.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(max_length=255, related_name='related_customer', to='shop.Order'),
        ),
    ]
