# Generated by Django 3.2.8 on 2021-10-27 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20211027_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('is_ready', 'order is ready'), ('in_progress', 'order in progress'), ('completed', 'new order'), ('completed', 'order is completed')], default='NEW', max_length=255),
        ),
    ]
